apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080