apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379